version: "3.8"

services:

  flask:
    build: ./
    volumes:
      - ./:/app
    ports:
      # public:local
      - "17821:5001"
    container_name: portable
    restart: always
    environment:
      - APP_NAME=portable